site_name: My Docs
site_name: DoTS documentation
site_url: https://dots-documentation.github.io/

nav:
    - DoTS: index.md
    - Publier un corpus: publishing-workflow.md
    - Dossier de dépôt: dots-project-folder.md
    - Cookbook:
        - cookbook/index.md
        - Périodiques: cookbook/periodical.md
        - Théâtre: cookbook/theater.md
    - DTS API: api.md

theme:
  name: material
  logo: img/logo-dots.png
  features:
    - navigation.indexes
    - content.code.annotate


extra_css:
  - css/custom.css
  - css/stackoverflow-light.min.css

extra_javascript:
  - js/custom.js
  - js/highlight.min.js

plugins:
      - macros
      - render_swagger:
          allow_arbitrary_locations: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
