site_name: My Docs
site_name: DoTS documentation
site_url: https://dots.documentation.com/
nav:
    - DoTS: index.md
    - Publier un corpus: publishing-workflow.md
    - Dossier de dépôt: dots-project-folder.md
    - DoTS Cookbook: cookbook.md
    - DTS API: api.md

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
